apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-example
  namespace: kafka-namespace
  labels:
    app: kafka-example
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-example
      labels:
        app: kafka-example
    spec:
      containers:
        - name: kafka-example
          image: yigitcanyontem/kafka-example:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka-example
