apiVersion: v1
kind: Service
metadata:
  name: kafka-example
  namespace: kafka-namespace
spec:
  selector:
    app: kafka-example
  ports:
    - port: 80
      targetPort: 8083
  type: LoadBalancer

#minikube service kafka --url -n kafka-namespace
#minikube service kafka-ui --url -n kafka-namespace
